//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.EFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int Id { get; set; }
        public int MemberID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
