//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.Pages.Designer {
    
    
    public partial class CustomerInputs {
        
        /// <summary>
        /// ctrl_ViewerPreviewReferences control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.ctrl_ViewerPreviewReferences ctrl_ViewerPreviewReferences;
        
        /// <summary>
        /// ctrl_CustomerInputs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.ctrl_CustomerInputs ctrl_CustomerInputs;
        
        /// <summary>
        /// ctrl_InputsSketchesGuide control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.ctrl_InputsSketchesGuide ctrl_InputsSketchesGuide;
        
        /// <summary>
        /// ctrl_ViewerPreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.ctrl_ViewerPreview ctrl_ViewerPreview;
    }
}
