//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.Pages.Designer {
    
    
    public partial class DesignCode {
        
        /// <summary>
        /// Ctrl_DesignCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.Ctrl_DesignCode Ctrl_DesignCode;
    }
}
