//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.Pages.Designer {
    
    
    public partial class NewProjectInformation {
        
        /// <summary>
        /// ctrl_NewProject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Designer.ctrl_NewProject ctrl_NewProject;
    }
}
