//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.Shawky ,Khaled, Mark &amp; Kareem.
        /// </summary>
        internal static string ApplicationDevelopers {
            get {
                return ResourceManager.GetString("ApplicationDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated Steel Design Package.
        /// </summary>
        internal static string ApplicationFullName {
            get {
                return ResourceManager.GetString("ApplicationFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDAZteel.
        /// </summary>
        internal static string ApplicationIdentifier {
            get {
                return ResourceManager.GetString("ApplicationIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.1.
        /// </summary>
        internal static string CurrentApplicationVersion {
            get {
                return ResourceManager.GetString("CurrentApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDAZteel Project Description.
        /// </summary>
        internal static string DefaultProjectDescription {
            get {
                return ResourceManager.GetString("DefaultProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDAZteel Project Name.
        /// </summary>
        internal static string DefaultProjectName {
            get {
                return ResourceManager.GetString("DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SavedDXF/.
        /// </summary>
        internal static string DXFPath {
            get {
                return ResourceManager.GetString("DXFPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SavedRobot/.
        /// </summary>
        internal static string RobotPath {
            get {
                return ResourceManager.GetString("RobotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDAZ Steel Package.
        /// </summary>
        internal static string siteTitle {
            get {
                return ResourceManager.GetString("siteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Savedwexbim/.
        /// </summary>
        internal static string wexbimPath {
            get {
                return ResourceManager.GetString("wexbimPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /xBIM-WebUI/tests/data/SampleHouse.wexbim.
        /// </summary>
        internal static string xBIMSample {
            get {
                return ResourceManager.GetString("xBIMSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SavedXML/.
        /// </summary>
        internal static string XMLPath {
            get {
                return ResourceManager.GetString("XMLPath", resourceCulture);
            }
        }
    }
}
