//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.Pages.Anonymous {
    
    
    public partial class Index {
        
        /// <summary>
        /// ctrl_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.MasterPages.MasterPagesControls.OxygenTemplate.Header ctrl_Header;
        
        /// <summary>
        /// ctrl_TemplatePictures control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Anonymous.ctrl_TemplatePictures ctrl_TemplatePictures;
        
        /// <summary>
        /// ctrl_Team control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.MasterPages.MasterPagesControls.OxygenTemplate.ctrl_Team ctrl_Team;
        
        /// <summary>
        /// ctrl_Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.MasterPages.MasterPagesControls.OxygenTemplate.ctrl_Contact ctrl_Contact;
    }
}
