//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANDAZ.PEB.WebUI.Pages.Anonymous {
    
    
    public partial class Login {
        
        /// <summary>
        /// Ctrl_LogIn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HANDAZ.PEB.WebUI.UserControls.Anonymous.Ctrl_LogIn Ctrl_LogIn;
    }
}
